Cli.2
takopian/CLI pull request #2
Opened 2021-02-24 12:57 UTC by takopian

Второе задание.

2021-02-27 21:17 UTC, FirstTimeInForever requested changes
Не работает пайп:
```
cat ../README.md | grep python
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    interpreter()
  File "app.py", line 15, in interpreter
    Executor(pipeline).execute()
  File "/Users/hans/stuff/trash/CLI/src/executor.py", line 21, in execute
    cur_result = command()
  File "/Users/hans/stuff/trash/CLI/src/commands.py", line 198, in __call__
    file = open(find_in, mode='r')
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Не обрабатываются ошибки:
```
grep asd asd
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    interpreter()
  File "app.py", line 15, in interpreter
    Executor(pipeline).execute()
  File "/Users/hans/stuff/trash/CLI/src/executor.py", line 21, in execute
    cur_result = command()
  File "/Users/hans/stuff/trash/CLI/src/commands.py", line 198, in __call__
    file = open(find_in, mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'asd'
```

2021-03-04 00:11 UTC, takopian commented
Добавил исправления в этот PR. Добавил Shell и потоки ввода вывода. В некоторых местах добавил обработку исключений. Для wc и grep теперь работают пайпы. Починил  проблему с модулями, теперь можно запустить как в документации это описано. Добавил некоторое количество тестов.

2021-03-06 23:31 UTC, FirstTimeInForever requested changes
Мне снова пришлось танцевать с бубном чтобы запустить. Укажите в документации способ запуска через докер и поправьте в `Dockerfile` `ENTRYPOINT` (сделайте так, чтобы у вас при старте контейнера запускался шелл).
Архитектура:
* Примените паттерн [абстрактная фабрика](https://refactoring.guru/design-patterns/abstract-factory) для того чтобы ваш парсер не был привязан к конкретным командам. Передавайте вашу фабрику в `Parser` (хотя лучше это делать на уровне `Executor`).
* Параметризируйте ваш шелл IO потоками и внутри команд пишите и читайте из них вместо `print`. Сейчас у вас гвоздями прибит `sys.stdout`.

Функционал:
* Не обрабатываются ошибки в аргументах, например `grep`:
```
grep -A
can only concatenate str (not "NoneType") to str
grep -A dfasd
invalid context length argument
```
* Не обрабатываются ошибки с пайпами:
```
echo some |
```
* Не работают подстановки:
```
x=1
echo "'$x'"
"' 1
 '"
```
```
x=1
echo "asd$x"
1
```
```
x=ex
y=it
$x$y
```
* Почему-то запускается внешний `wc` (если перед ним стояла другая внешняя команда):
```
git status | wc
fatal: not a git repository (or any of the parent directories): .git
      0       0       0
```
Есть ощущение, что приложение рандомно ломается без сообщения каких-либо ошибок. Пожалуйста внимательно потестируйте ваше приложение и исправьте ошибки и архитектурные замечания. Пока `3/7`.

2021-03-06 23:31 UTC, FirstTimeInForever commented on Dockerfile
> +ENTRYPOINT bash
Лучше тут запускать не баш, а ваш шелл.

2021-03-06 23:31 UTC, FirstTimeInForever commented on src/executor.py
> +        self.command_dict = {'cat': Cat, 'echo': Echo, 'wc': WC, 'pwd': PWD, 'exit': Exit, 'grep': Grep}
Кажется, это тут не используется.

2021-03-06 23:31 UTC, FirstTimeInForever commented on src/parser.py
> +commandDict = {'cat': Cat, 'echo': Echo, 'wc': WC, 'pwd': PWD, 'exit': Exit, 'grep': Grep}
Ожидалось, что это будет вынесено в абстрактную фабрику. Иначе у вас никто не сможет кастомизировать набор поддерживаемых команд не изменяя код парсера.

2021-03-23 23:11 UTC, FirstTimeInForever commented
Я забыл что `grep` теперь считается как отдельное задание (в прошлом году была другая система оценки), поэтому отдельно за греп: `6/10`. Основной поинт - плохая обработка ошибок, т. к. из-за этого часто ломаются последующие команды.

2021-04-04 18:15 UTC, takopian commented
Добавил диаграммы в этот пул реквест.

2021-04-15 07:16 UTC, FirstTimeInForever reviewed
* На диаграмме компонентов не указано через какие интерфейсы связываются компоненты.

`5/6`.

2024-05-05 16:54 UTC, merged